mqtt:
  client:
    protocol: 4      # MQTTv311
  connection:
    host: 134.130.20.42
    port: 1883
    keepalive: 60
  private_path: device/001
  account:
    username: acdc
    password: connectedDriving#2022!
bridge:
  # Station A
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: definitions.msg:IkaObjectList
    topic_from: objectList_a
    topic_to: /topicA
  # Station B
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: definitions.msg:IkaObjectList
    topic_from: objectList_b
    topic_to: /topicB
  # Ground Truth
  - factory: mqtt_bridge.bridge:MqttToRosBridge
    msg_type: definitions.msg:IkaObjectList
    topic_from: objectList_gt
    topic_to: /topicGT